steps:
  # Compile
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: [ "clean package" ]
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/strong-market-322501/customer-service-0.1', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/strong-market-322501/customer-service-0.1']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'customer-service', '--image', 'gcr.io/strong-market-322501/customer-service-0.1', '--region', 'REGION']
images:
  - gcr.io/strong-market-322501/customer-service-0.1